### ISSUE TITLE
Proper network protection

### ISSUE THREAD

**Issue by dunkfordyce** [siemens/edgeshark#41]
The manual says:

```
Warning

This quick start deployment will expose TCP port 5001 also to clients external to your host. Make sure to have proper network protection in place.
```

This seems non trivial... a lot of messing with iptables.  Could the application provide a simple whitelist argument or something similar to make this easier? Or is there another simple option I am not aware of?

**Comment by thediveo** [comment]
The general problem here is that there are no generally established mechanisms, so it heavily depends on your particular infrastructure, endpoint protection, and TRA. There are what I would consider typical deployments, see below for the general idea.

That said, the first deployment example deploys the front Edgeshark service only on [localhost/127.0.0.1](https://github.com/siemens/edgeshark/blob/59c1109320db9ded7373d2b46609718e49f15436/deployments/wget/docker-compose-localhost.yaml#L58):
```yaml
ports:
- "127.0.0.1:5001:5001"
```

The second deployment example you are probably referring to requires a correctly working perimeter setup, where you trust to only allowed clients to be able to connect to the host with the Edgeshark service.

Docker itself does not support any source IP whitelisting as far as I'm aware of. As you point out, there's the iptables/nftables option.

A more container-like deployment is to my (limited) experience more along the lines of deploying an HTTP/Websocket proxy, such as traeffic and nginx. In this situation, you would not expose Edgeshark by port forwarding from the host, but instead only expose your proxy. Your proxy then forwards a specific route like `/edgeshark` to external clients and forwarding the traffic via an internal Docker custom network to the Edgeshark service. You'll need to modify the Edgeshark deployment to attach the Edgeshark service/container to your proxy redirection network for this to work.

You should rewrite the original URL when forwarding from the proxy to Edgeshark, so that `/edgeshark` becomes `/`; in addition, make sure that your forwarding proxy sets the appropriate headers `X-Forwarded-Prefix` or `X-Forwarded-Uri`. These are needed in order for the web UI's DOM routing to work correctly with the backend routes. Details here: https://github.com/thediveo/spaserve/blob/d30c2f1060c856f3a7f399a6bffd2d5cd12273d0/spa.go#L31

Handling TLS and certificates inside Edgeshark would IMHO only make sense in deployment environments with a proper TLS termination and certificate handling. On top of this, this would also sensibly handle access control to the service, such as via JWTs, and with the necessary wiring-up. From what I see this is always clearly separated from the services themselves, and realized using sidecars and aux services, such as in istio. There doesn't seem to be any low-key solution that is sufficiently reliable and safe and that can be directly integrated without getting into a mess.

**Comment by thediveo** [comment]
When you click on a "shark fin" in the UI, this triggers an external program execution: `wireshark` gets started and CLI args passed to it that tell Wireshark to start the external capture "plugin" (binary).

We're passing the "basename" of the URL to the extcap, and that contains the hostname you're using in your browser session. The extcap now wants to establish an HTTP/Websocket session. As the capture session actually is Websocket, we have to map:
- browser UI URL scheme is "http://" translates to "ws://"
- browser UI URL scheme is "https://" translates to "wss://"

The extcap binary gets started by the Wireshark process, so it runs in the same UID, etc. As we're "transferring" your web UI URL, the plugin must be able to properly resolve the hostname from this URL. Somehow your host's DNS setup doesn't cover for your split-horizon DNS and your host DNS recursive resolver seems to forward to Google's DNS at 8.8.8.8.

My first guess would be to try with a `/etc/hosts` and check that the extcap picks up its settings correctly. Otherwise, can you reach the web UI using the host IP instead of a DNS FQDN?

There's also a fallback way of capturing, not only for Apple macOS users: start Wireshark as normal and then click on the gear icon next to the "Docker host capture ... (mobyshark)", as shown next. 

![image](https://github.com/siemens/edgeshark/assets/6920158/7d066a5e-ab90-453f-ab63-60b9aaa0529c)

In the extcap dialog shown next, enter an http/https URL, using the host's IP address where the proxy is, and the optional route, such as `/edgeshark`. Then click on the refresh button next to the empty containers drop-down list. If things work correctly, you should see your workload list.

**Comment by dunkfordyce** [comment]
Thank you! It works with the ip address (which isnt a huge problem because im using a specific port anyway). For some reason wireshark seems to ignore my hosts file on windows, I have no idea why... But I am now able to capture via the web interface.

**Comment by dunkfordyce** [comment]
Thank you again
